autofetch_sources: True

networks:
  default: mainnet-fork
dotenv: .env

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - smartcontractkit/chainlink@1.10.0

compiler:
    evm_version: "paris"
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
          - "@chainlink=smartcontractkit/chainlink@1.10.0"
        optimizer:
          enabled: true
          runs: 200
          details:
            cse: true
            yul: true
